<?xml version="1.0"?>
<robot xmlns:xacro="http://wiki.ros.org/xacro">

  <xacro:include filename="$(find suii_description)/urdf/suii_transmission.xacro" />
  <xacro:include filename="$(find suii_description)/urdf/suii_gazebo.xacro" />

  <xacro:macro name="cylinder_inertial" params="radius length mass *origin">
    <inertial>
      <mass value="${mass}" />
      <xacro:insert_block name="origin" />
      <inertia ixx="${0.0833333 * mass * (3 * radius * radius + length * length)}" ixy="0.0" ixz="0.0"
        iyy="${0.0833333 * mass * (3 * radius * radius + length * length)}" iyz="0.0"
        izz="${0.5 * mass * radius * radius}" />
    </inertial>
  </xacro:macro>

  <xacro:macro name="suii_robot" params="prefix joint_limited
    shoulder_pan_lower_limit:=${-pi}    shoulder_pan_upper_limit:=${pi}
    shoulder_lift_lower_limit:=${-pi}    shoulder_lift_upper_limit:=${pi}
    elbow_joint_lower_limit:=${-pi}    elbow_joint_upper_limit:=${pi}

    wrist_1_lower_limit:=${-pi}    wrist_1_upper_limit:=${pi}
    wrist_2_lower_limit:=${-pi}    wrist_2_upper_limit:=${pi}
    wrist_3_lower_limit:=${-pi}    wrist_3_upper_limit:=${pi}

    ur3_mount_lower_limit:=${-pi}    ur3_mount_upper_limit:=${pi}

    transmission_hw_interface:=hardware_interface/PositionJointInterface
    safety_limits:=false safety_pos_margin:=0.15
    safety_k_position:=20">

    <!-- Inertia parameters -->
    <xacro:property name="bottom_mass" value="2.0" />
    <xacro:property name="shoulder_mass" value="2.0" />
    <xacro:property name="upper_arm_mass" value="3.42" />
    <xacro:property name="forearm_mass" value="1.26" />
    <xacro:property name="wrist_1_mass" value="0.8" />
    <xacro:property name="wrist_2_mass" value="0.8" />
    <xacro:property name="wrist_3_mass" value="0.35"/>
    <xacro:property name="frame_mass" value="20.5"/>
    <xacro:property name="ur3_mount_plate" value="0.08"/>
    <xacro:property name="wheel_mass" value="0.37904"/>

    <xacro:property name="gripper_base_mass" value="0.500"/>
    <xacro:property name="Tilted_link_mass" value="0.035"/>
    <xacro:property name="straight_link_mass" value="0.042"/>
    <xacro:property name="finger_mass" value="0.035"/>




    <xacro:property name="shoulder_cog" value="0.0 -0.02 0.0" />
    <xacro:property name="upper_arm_cog" value="0.13 0.0 0.1157" />
    <xacro:property name="forearm_cog" value="0.05 0.0 0.0238" />
    <xacro:property name="wrist_1_cog" value="0.0 0.0 0.01" />
    <xacro:property name="wrist_2_cog" value="0.0 0.0 0.01" />
    <xacro:property name="wrist_3_cog" value="0.0 0.0 -0.02" />

    <!-- Kinematic model -->
    <!-- Properties from urcontrol.conf -->
    <xacro:property name="d1" value="0.1519" />
    <xacro:property name="a2" value="-0.24365" />
    <xacro:property name="a3" value="-0.21325" />
    <xacro:property name="d4" value="0.11235" />
    <xacro:property name="d5" value="0.08535" />
    <xacro:property name="d6" value="0.0819" />

    <!-- Arbitrary offsets for shoulder/elbow joints -->
    <xacro:property name="shoulder_offset" value="0.1198" />  <!-- measured from model -->
    <xacro:property name="elbow_offset" value="-0.0925" /> <!-- measured from model -->

    <!-- link lengths used in model -->
    <xacro:property name="shoulder_height" value="${d1}" />
    <xacro:property name="upper_arm_length" value="${-a2}" />
    <xacro:property name="forearm_length" value="${-a3}" />
    <xacro:property name="wrist_1_length" value="${d4 - elbow_offset - shoulder_offset}" />
    <xacro:property name="wrist_2_length" value="${d5}" />
    <xacro:property name="wrist_3_length" value="${d6}" />

    <!-- sensor properties-->
    <xacro:property name="sonar_link" value="-0.05" /> <!-- Size of square 'sonar' box -->
    <xacro:property name="laser_link" value="-0.001" /> <!-- Size of square 'sonar' box -->
    <xacro:property name="height" value="0.3" /> <!-- height sensors-->
    <xacro:property name="axel_offset" value="0.05" /> <!-- offset placement -->

    <gazebo>
	    <plugin name="omni_steering" filename="libgazebo_ros_planar_move.so">
	      <commandTopic>/cmd_vel</commandTopic>
	      <odometryTopic>/odom</odometryTopic>
	      <odometryFrame>/odom</odometryFrame>
	      <odometryRate>50.0</odometryRate>
	      <robotBaseFrame>base_link</robotBaseFrame>
	      <publishTF>true</publishTF>
	    </plugin>
	  </gazebo>
    <gazebo>
    	<plugin name="ros_control" filename="libgazebo_ros_control.so">
      	<!--robotNamespace>/</robotNamespace-->
      	<!--robotSimType>gazebo_ros_control/DefaultRobotHWSim</robotSimType-->
    	</plugin>

<!--
    <plugin name="gazebo_ros_power_monitor_controller" filename="libgazebo_ros_power_monitor.so">
      <alwaysOn>true</alwaysOn>
      <updateRate>1.0</updateRate>
      <timeout>5</timeout>
      <powerStateTopic>power_state</powerStateTopic>
      <powerStateRate>10.0</powerStateRate>
      <fullChargeCapacity>87.78</fullChargeCapacity>
      <dischargeRate>-474</dischargeRate>
      <chargeRate>525</chargeRate>
      <dischargeVoltage>15.52</dischargeVoltage>
      <chargeVoltage>16.41</chargeVoltage>
    </plugin>
-->
    </gazebo>

    <link name="${prefix}base_link" >
      <visual>
        <geometry>
          <mesh filename="package://suii_description/meshes/suii/visual/base_link.dae"/>
        </geometry>
        <material name="">
          <color rgba="0.752941176470588 0.752941176470588 0.752941176470588 1"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://suii_description/meshes/suii/collision/base_link.stl"/>
        </geometry>
      </collision>
      <inertial>
        <mass value= "${frame_mass}"/>
        <inertia ixx="0.34725" ixy="0.012191" ixz="1.1509E-06" iyy="0.91352" iyz="1.7554E-06" izz="0.66499"/>
        <origin xyz="0.15 -0.000252178578867549 0.0919059339213158"  rpy="0 0 0" />
      </inertial>
    </link>
    <joint name="${prefix}frame_mount_joint" type="fixed">
      <parent link="${prefix}base_link" />
      <child link = "${prefix}ur3_mount" />
      <origin xyz="-0.20331 0.0 0.16" rpy="0.0 0.0 3.14" />
      <axis xyz="0 0 1" />
    </joint>

    <link name="${prefix}ur3_mount">
      <visual>
        <geometry>
          <mesh filename="package://suii_description/meshes/suii/visual/ur3_mount.dae"/>
        </geometry>
        <material name="LightGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://suii_description/meshes/suii/collision/ur3_mount.stl"/>
        </geometry>
      </collision>
      <inertial>
        <mass value= "${ur3_mount_plate}"/>
        <inertia ixx="0.00013877" ixy="1.8488E-22" ixz="-3.1995E-06" iyy="0.00027709" iyz="-3.5837E-22" izz="-3.5837E-22"/>
        <origin xyz="0.0 0.0 0.0"  rpy="0 0 0" />
      </inertial>
    </link>

    <joint name="${prefix}left_front_wheel_joint" type="continuous">
      <parent link="${prefix}base_link" />
      <child link = "${prefix}left_front_wheel" />
      <origin xyz="-0.154701515190169 -0.166841606388669 0.038" rpy="-1.57079632679489 -1.19435213873094 0" />
      <axis xyz="0 0 1" />
    </joint>

    <link name="${prefix}left_front_wheel">
      <visual>
        <geometry>
          <mesh filename="package://suii_description/meshes/suii/visual/left_front_wheel.dae"/>
        </geometry>
        <material name="LightGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://suii_description/meshes/suii/collision/left_front_wheel.stl"/>
        </geometry>
      </collision>
      <inertial>
        <mass value= "${wheel_mass}"/>
        <inertia ixx="0.00037409" ixy="2.9355E-20" ixz="2.4641E-12" iyy="0.00037409" iyz="4.7724E-12" izz="0.00061547"/>
        <origin xyz="6.3835E-11 -1.4771E-10 -0.030043"  rpy="0 0 0" />
      </inertial>
    </link>

    <joint name="${prefix}left_back_wheel_joint" type="continuous">
      <parent link="${prefix}base_link" />
      <child link = "${prefix}left_back_wheel" />
      <origin xyz="0.154847909681733 -0.166841606388672 0.038" rpy="-1.5707963267949 0.0140924552640228 0" />
      <axis xyz="0 0 -1" />
    </joint>

    <link name="${prefix}left_back_wheel">
      <visual>
        <geometry>
          <mesh filename="package://suii_description/meshes/suii/visual/left_back_wheel.dae"/>
        </geometry>
        <material name="LightGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://suii_description/meshes/suii/collision/left_back_wheel.stl"/>
        </geometry>
      </collision>
      <inertial>
        <mass value= "${wheel_mass}"/>
        <inertia ixx="0.00037409" ixy="2.9355E-20" ixz="2.4641E-12" iyy="0.00037409" iyz="4.7724E-12" izz="0.00061547"/>
        <origin xyz="6.3835E-11 -1.4771E-10 -0.030043"  rpy="0 0 0" />
      </inertial>
    </link>

    <joint name="${prefix}right_front_wheel_joint" type="continuous">
      <parent link="${prefix}base_link" />
      <child link = "${prefix}right_front_wheel" />
      <origin xyz="-0.154701515190171 0.165835545628008 0.038" rpy="1.5707963267949 -0.277347631659683 0" />
      <axis xyz="0 0 -1" />
    </joint>

    <link name="${prefix}right_front_wheel">
      <visual>
        <geometry>
          <mesh filename="package://suii_description/meshes/suii/visual/right_front_wheel.dae"/>
        </geometry>
        <material name="LightGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://suii_description/meshes/suii/collision/right_front_wheel.stl"/>
        </geometry>
      </collision>
      <inertial>
        <mass value= "${wheel_mass}"/>
        <inertia ixx="0.00037409" ixy="2.9355E-20" ixz="2.4641E-12" iyy="0.00037409" iyz="4.7724E-12" izz="0.00061547"/>
        <origin xyz="6.3835E-11 -1.4771E-10 -0.030043"  rpy="0 0 0" />
      </inertial>
    </link>

    <joint name="${prefix}right_back_wheel_joint" type="continuous">
      <parent link="${prefix}base_link" />
      <child link = "${prefix}right_back_wheel" />
      <origin xyz="0.15485 0.16584 0.038" rpy="1.5708 -0.43657 0" />
      <axis xyz="0 0 1" />
    </joint>

    <link name="${prefix}right_back_wheel">
      <visual>
        <geometry>
          <mesh filename="package://suii_description/meshes/suii/visual/right_back_wheel.dae"/>
        </geometry>
        <material name="LightGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://suii_description/meshes/suii/collision/right_back_wheel.stl"/>
        </geometry>
      </collision>
      <inertial>
        <mass value= "${wheel_mass}"/>
        <inertia ixx="0.00037409" ixy="2.9355E-20" ixz="2.4641E-12" iyy="0.00037409" iyz="4.7724E-12" izz="0.00061547"/>
        <origin xyz="6.3835E-11 -1.4771E-10 -0.030043"  rpy="0 0 0" />
      </inertial>
    </link>

    <joint name="${prefix}ur3_mount_joint" type="revolute">
      <parent link="${prefix}ur3_mount" />
      <child link = "${prefix}bottom_link" />
      <origin xyz="0.0 0.0 0.008" rpy="0.0 0.0 0.0" />
      <axis xyz="0 0 1" />
      <xacro:unless value="${joint_limited}">
        <limit lower="${-2.0 * pi}" upper="${2.0 * pi}" effort="330.0" velocity="2.16"/>
        <xacro:if value="${safety_limits}">
          <safety_controller soft_lower_limit="${-2.0 * pi + safety_pos_margin}" soft_upper_limit="${2.0 * pi - safety_pos_margin}" k_position="${safety_k_position}" k_velocity="0.0"/>
        </xacro:if>
      </xacro:unless>
      <xacro:if value="${joint_limited}">
        <limit lower="${shoulder_pan_lower_limit}" upper="${shoulder_pan_upper_limit}" effort="330.0" velocity="2.16"/>
        <xacro:if value="${safety_limits}">
          <safety_controller soft_lower_limit="${ur3_mount_lower_limit + safety_pos_margin}" soft_upper_limit="${ur3_mount_upper_limit - safety_pos_margin}" k_position="${safety_k_position}" k_velocity="0.0"/>
        </xacro:if>
      </xacro:if>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>

    <link name="${prefix}bottom_link">
      <visual>
        <geometry>
          <mesh filename="package://suii_description/meshes/suii/visual/bottom_link.dae"/>
        </geometry>
        <material name="LightGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://suii_description/meshes/suii/collision/bottom_link.stl"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertial radius="0.075" length="0.178" mass="${bottom_mass}">
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
      </xacro:cylinder_inertial>
    </link>

    <joint name="${prefix}shoulder_pan_joint" type="revolute">
      <parent link="${prefix}bottom_link" />
      <child link = "${prefix}shoulder_link" />
      <origin xyz="0.0 0.0 ${shoulder_height}" rpy="0.0 0.0 0.0" />
      <axis xyz="0 0 1" />
      <xacro:unless value="${joint_limited}">
        <limit lower="${-3.0 * pi}" upper="${1.0 * pi}" effort="330.0" velocity="2.16"/>
        <xacro:if value="${safety_limits}">
          <safety_controller soft_lower_limit="${-3.0 * pi + safety_pos_margin}" soft_upper_limit="${1.0 * pi - safety_pos_margin}" k_position="${safety_k_position}" k_velocity="0.0"/>
        </xacro:if>
      </xacro:unless>
      <xacro:if value="${joint_limited}">
        <limit lower="${shoulder_pan_lower_limit}" upper="${shoulder_pan_upper_limit}" effort="330.0" velocity="2.16"/>
        <xacro:if value="${safety_limits}">
          <safety_controller soft_lower_limit="${shoulder_pan_lower_limit + safety_pos_margin}" soft_upper_limit="${shoulder_pan_upper_limit - safety_pos_margin}" k_position="${safety_k_position}" k_velocity="0.0"/>
        </xacro:if>
      </xacro:if>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>

    <link name="${prefix}shoulder_link">
      <visual>
        <geometry>
          <mesh filename="package://suii_description/meshes/suii/visual/shoulder.dae"/>
        </geometry>
        <material name="LightGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://suii_description/meshes/suii/collision/shoulder.stl"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertial radius="0.075" length="0.178" mass="${shoulder_mass}">
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
      </xacro:cylinder_inertial>
    </link>

    <joint name="${prefix}shoulder_lift_joint" type="revolute">
      <parent link="${prefix}shoulder_link" />
      <child link = "${prefix}upper_arm_link" />
      <origin xyz="0.0 ${shoulder_offset} 0.0" rpy="0.0 0.0 0.0" />
      <axis xyz="0 1 0" />
      <xacro:unless value="${joint_limited}">
        <limit lower="${-2.5 * pi}" upper="${1.5 * pi}" effort="330.0" velocity="2.16"/>
        <xacro:if value="${safety_limits}">
          <safety_controller soft_lower_limit="${-2.5 * pi + safety_pos_margin}" soft_upper_limit="${1.5 * pi - safety_pos_margin}" k_position="${safety_k_position}" k_velocity="0.0"/>
        </xacro:if>
      </xacro:unless>
      <xacro:if value="${joint_limited}">
        <limit lower="${shoulder_lift_lower_limit}" upper="${shoulder_lift_upper_limit}" effort="330.0" velocity="2.16"/>
        <xacro:if value="${safety_limits}">
          <safety_controller soft_lower_limit="${shoulder_lift_lower_limit + safety_pos_margin}" soft_upper_limit="${shoulder_lift_upper_limit - safety_pos_margin}" k_position="${safety_k_position}" k_velocity="0.0"/>
        </xacro:if>
      </xacro:if>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>

    <link name="${prefix}upper_arm_link">
      <visual>
        <geometry>
          <mesh filename="package://suii_description/meshes/suii/visual/upperarm.dae"/>
        </geometry>
        <material name="LightGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://suii_description/meshes/suii/collision/upperarm.stl"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertial radius="0.075" length="${-a2}" mass="${upper_arm_mass}">
        <origin xyz="0.0 0.0 ${-a2/2.0}" rpy="0 0 0" />
      </xacro:cylinder_inertial>
    </link>

    <joint name="${prefix}elbow_joint" type="revolute">
      <parent link="${prefix}upper_arm_link" />
      <child link = "${prefix}forearm_link" />
      <origin xyz="0.0 ${elbow_offset} ${upper_arm_length}" rpy="0.0 0.0 0.0" />
      <axis xyz="0 1 0" />
      <xacro:unless value="${joint_limited}">
        <limit lower="${-pi}" upper="${pi}" effort="150.0" velocity="3.15"/>
        <xacro:if value="${safety_limits}">
          <safety_controller soft_lower_limit="${-2.0 * pi + safety_pos_margin}" soft_upper_limit="${2.0 * pi - safety_pos_margin}" k_position="${safety_k_position}" k_velocity="0.0"/>
        </xacro:if>
      </xacro:unless>
      <xacro:if value="${joint_limited}">
        <limit lower="${elbow_joint_lower_limit}" upper="${elbow_joint_upper_limit}" effort="150.0" velocity="3.15"/>
        <xacro:if value="${safety_limits}">
          <safety_controller soft_lower_limit="${elbow_joint_lower_limit + safety_pos_margin}" soft_upper_limit="${elbow_joint_upper_limit - safety_pos_margin}" k_position="${safety_k_position}" k_velocity="0.0"/>
        </xacro:if>
      </xacro:if>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>

    <link name="${prefix}forearm_link">
      <visual>
        <geometry>
          <mesh filename="package://suii_description/meshes/suii/visual/forearm.dae"/>
        </geometry>
        <material name="LightGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://suii_description/meshes/suii/collision/forearm.stl"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertial radius="0.075" length="${-a3}" mass="${forearm_mass}">
        <origin xyz="0.0 0.0 ${-a3/2.0}" rpy="0 0 0" />
      </xacro:cylinder_inertial>
    </link>

    <joint name="${prefix}wrist_1_joint" type="revolute">
      <parent link="${prefix}forearm_link" />
      <child link = "${prefix}wrist_1_link" />
      <origin xyz="0.0 0.0 ${forearm_length}" rpy="0.0 ${pi / 2.0} 0.0" />
      <axis xyz="0 1 0" />
      <xacro:unless value="${joint_limited}">
        <limit lower="${-2.0 * pi}" upper="${2.0 * pi}" effort="54.0" velocity="3.2"/>
        <xacro:if value="${safety_limits}">
          <safety_controller soft_lower_limit="${-2.0 * pi + safety_pos_margin}" soft_upper_limit="${2.0 * pi - safety_pos_margin}" k_position="${safety_k_position}" k_velocity="0.0"/>
        </xacro:if>
      </xacro:unless>
      <xacro:if value="${joint_limited}">
        <limit lower="${wrist_1_lower_limit}" upper="${wrist_1_upper_limit}" effort="54.0" velocity="3.2"/>
        <xacro:if value="${safety_limits}">
          <safety_controller soft_lower_limit="${wrist_1_lower_limit + safety_pos_margin}" soft_upper_limit="${wrist_1_upper_limit - safety_pos_margin}" k_position="${safety_k_position}" k_velocity="0.0"/>
        </xacro:if>
      </xacro:if>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>

    <link name="${prefix}wrist_1_link">
      <visual>
        <geometry>
          <mesh filename="package://suii_description/meshes/suii/visual/wrist1.dae"/>
        </geometry>
        <material name="LightGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://suii_description/meshes/suii/collision/wrist1.stl"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertial radius="0.075" length="0.12" mass="${wrist_1_mass}">
        <origin xyz="0.0 ${wrist_1_length} 0.0" rpy="0 0 0" />
      </xacro:cylinder_inertial>
    </link>

    <joint name="${prefix}wrist_2_joint" type="revolute">
      <parent link="${prefix}wrist_1_link" />
      <child link = "${prefix}wrist_2_link" />
      <origin xyz="0.0 ${wrist_1_length} 0.0" rpy="0.0 0.0 0.0" />
      <axis xyz="0 0 1" />
      <xacro:unless value="${joint_limited}">
        <limit lower="${-2.0 * pi}" upper="${2.0 * pi}" effort="54.0" velocity="3.2"/>
        <xacro:if value="${safety_limits}">
          <safety_controller soft_lower_limit="${-2.0 * pi + safety_pos_margin}" soft_upper_limit="${2.0 * pi - safety_pos_margin}" k_position="${safety_k_position}" k_velocity="0.0"/>
        </xacro:if>
      </xacro:unless>
      <xacro:if value="${joint_limited}">
        <limit lower="${wrist_2_lower_limit}" upper="${wrist_2_upper_limit}" effort="54.0" velocity="3.2"/>
        <xacro:if value="${safety_limits}">
          <safety_controller soft_lower_limit="${wrist_2_lower_limit + safety_pos_margin}" soft_upper_limit="${wrist_2_upper_limit - safety_pos_margin}" k_position="${safety_k_position}" k_velocity="0.0"/>
        </xacro:if>
      </xacro:if>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>

    <link name="${prefix}wrist_2_link">
      <visual>
        <geometry>
          <mesh filename="package://suii_description/meshes/suii/visual/wrist2.dae"/>
        </geometry>
        <material name="LightGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://suii_description/meshes/suii/collision/wrist2.stl"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertial radius="0.075" length="0.12" mass="${wrist_2_mass}">
        <origin xyz="0.0 0.0 ${wrist_2_length}" rpy="0 0 0" />
      </xacro:cylinder_inertial>
    </link>

    <joint name="${prefix}wrist_3_joint" type="revolute">
      <parent link="${prefix}wrist_2_link" />
      <child link = "${prefix}wrist_3_link" />1.4771E-10
      <origin xyz="0.0 0.0 ${wrist_2_length}" rpy="0.0 0.0 0.0" />
      <axis xyz="0 1 0" />
      <xacro:unless value="${joint_limited}">
        <limit lower="${-2.0 * pi}" upper="${2.0 * pi}" effort="54.0" velocity="3.2"/>
        <xacro:if value="${safety_limits}">
          <safety_controller soft_lower_limit="${-2.0 * pi + safety_pos_margin}" soft_upper_limit="${2.0 * pi - safety_pos_margin}" k_position="${safety_k_position}" k_velocity="0.0"/>
        </xacro:if>
      </xacro:unless>
      <xacro:if value="${joint_limited}">
        <limit lower="${wrist_3_lower_limit}" upper="${wrist_3_upper_limit}" effort="54.0" velocity="3.2"/>
        <xacro:if value="${safety_limits}">
          <safety_controller soft_lower_limit="${wrist_3_lower_limit + safety_pos_margin}" soft_upper_limit="${wrist_3_upper_limit - safety_pos_margin}" k_position="${safety_k_position}" k_velocity="0.0"/>
        </xacro:if>
      </xacro:if>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>

    <link name="${prefix}wrist_3_link">
      <visual>
        <geometry>
          <mesh filename="package://suii_description/meshes/suii/visual/wrist3.dae"/>
        </geometry>
        <material name="LightGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://suii_description/meshes/suii/collision/wrist3.stl"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertial radius="0.032" length="0.04" mass="${wrist_3_mass}">
        <origin xyz="0.0 ${wrist_3_length - 0.02} 0.0" rpy="${pi/2} 0 0" />
      </xacro:cylinder_inertial>
    </link>

    <joint name="${prefix}wrist_3_link" type="fixed">
      <parent link="${prefix}wrist_3_link" />
      <child link = "${prefix}gripper_base"/>
      <origin xyz="0 0.08 0" rpy="0 1.57 -1.57" />
      <axis xyz="0 1 0" />
      <!-- <xacro:unless value="${joint_limited}">
        <limit lower="${-2.0 * pi}" upper="${2.0 * pi}" effort="54.0" velocity="3.2"/>
        <xacro:if value="${safety_limits}">
          <safety_controller soft_lower_limit="${-2.0 * pi + safety_pos_margin}" soft_upper_limit="${2.0 * pi - safety_pos_margin}" k_position="${safety_k_position}" k_velocity="0.0"/>
        </xacro:if>
      </xacro:unless>
      <xacro:if value="${joint_limited}">
        <limit lower="${wrist_3_lower_limit}" upper="${wrist_3_upper_limit}" effort="54.0" velocity="3.2"/>
        <xacro:if value="${safety_limits}">
          <safety_controller soft_lower_limit="${wrist_3_lower_limit + safety_pos_margin}" soft_upper_limit="${wrist_3_upper_limit - safety_pos_margin}" k_position="${safety_k_position}" k_velocity="0.0"/>
        </xacro:if>
      </xacro:if>
      <dynamics damping="0.0" friction="0.0"/> -->
    </joint>

    <link name="${prefix}gripper_base">
      <visual>
        <geometry>
          <mesh filename="package://suii_description/meshes/suii/visual/gripper_base.STL"/>
        </geometry>
        <material name="LightGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://suii_description/meshes/suii/collision/gripper_base.STL"/>
        </geometry>
      </collision>
      <inertial>
        <mass value= "${gripper_base_mass}"/>
        <!-- <inertia ixx="3.1166E-10" ixy="-4.678E-12" ixz="1.861E-11" iyy="8.724E-10" iyz="5.6254E-11" izz="6.5089E-10"/>  -->
        <inertia ixx="0" ixy="0" ixz="0" iyy="0" iyz="0" izz="0"/>
        <origin xyz="0 0 0"  rpy="0 0 0" />
      </inertial>
    </link>

    <joint name="${prefix}leftTilted_link" type="revolute">
      <parent link="${prefix}gripper_base" />
      <child link = "${prefix}leftTilted_link" />
      <origin xyz="0.04625 0.0035 -0.041" rpy="${pi} ${pi} 0" />
      <axis xyz="0 1 0" />
      <limit lower="${-1.6}" upper="${0}" effort="54.0" velocity="3.2"/>

      <dynamics damping="0.0" friction="0.0"/>
    </joint>

    <link name="${prefix}leftTilted_link">
      <visual>
        <geometry>
          <mesh filename="package://suii_description/meshes/suii/visual/leftTilted_link.STL"/>
        </geometry>
        <material name="LightGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://suii_description/meshes/suii/collision/leftTilted_link.STL"/>
        </geometry>
      </collision>
      <inertial>
        <mass value= "${Tilted_link_mass}"/>
        <inertia ixx="2.6985E-06" ixy="-2.1237E-06" ixz="-3.3979E-09" iyy="1.5914E-05" iyz="-5.2468E-08" izz="1.7824E-05"/>
        <origin xyz="0 0 0"  rpy="0 0 0" />
      </inertial>
    </link>

    <joint name="${prefix}rightTilted_link" type="revolute">
      <parent link="${prefix}gripper_base" />
      <child link = "${prefix}rightTilted_link" />
      <origin xyz="-0.04625 0.0035 -0.041" rpy="${pi} ${pi} 0" />
      <axis xyz="0 1 0" />
      <limit lower="${0}" upper="${1.6}" effort="54.0" velocity="3.2"/>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>

    <link name="${prefix}rightTilted_link">
      <visual>
        <geometry>
          <mesh filename="package://suii_description/meshes/suii/visual/rightTilted_link.STL"/>
        </geometry>
        <material name="LightGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://suii_description/meshes/suii/collision/rightTilted_link.STL"/>
        </geometry>
      </collision>
      <inertial>
        <mass value= "${Tilted_link_mass}"/>
        <inertia ixx="3.0184E-06" ixy="-2.1488E-06" ixz="-2.0304E-06" iyy="1.6193E-05" iyz="-2.3521E-07" izz="1.7863E-05"/>
        <origin xyz="0 0 0"  rpy="0 0 0" />
      </inertial>
    </link>

    <joint name="${prefix}rightStraight_link" type="revolute">
      <parent link="${prefix}gripper_base" />
      <child link = "${prefix}rightStraight_link" />
      <origin xyz="-0.02125 0.0035 -0.061" rpy="${pi} ${pi} 0" />
      <axis xyz="0 1 0" />
      <limit lower="${0}" upper="${1.6}" effort="54.0" velocity="3.2"/>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>

    <link name="${prefix}rightStraight_link">
      <visual>
        <geometry>
          <mesh filename="package://suii_description/meshes/suii/visual/rightStraight_link.STL"/>
        </geometry>
        <material name="LightGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://suii_description/meshes/suii/collision/rightStraight_link.STL"/>
        </geometry>
      </collision>
      <inertial>
        <mass value= "${straight_link_mass}"/>
        <inertia ixx="2.5229E-05" ixy="4.9094E-09" ixz="-4.3357E-08" iyy="2.2844E-05" iyz="2.9677E-06" izz="3.5161E-06"/>
        <origin xyz="0 0 0"  rpy="0 0 0" />
      </inertial>
    </link>

    <joint name="${prefix}leftStraight_link" type="revolute">
      <parent link="${prefix}gripper_base" />
      <child link = "${prefix}leftStraight_link" />
      <origin xyz="0.02125 0.0035 -0.061" rpy="${pi} ${pi} 0" />
      <axis xyz="0 1 0" />
      <limit lower="${-1.6}" upper="${0}" effort="54.0" velocity="3.2"/>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>

    <link name="${prefix}leftStraight_link">
      <visual>
        <geometry>
          <mesh filename="package://suii_description/meshes/suii/visual/leftStraight_link.STL"/>
        </geometry>
        <material name="LightGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://suii_description/meshes/suii/collision/leftStraight_link.STL"/>
        </geometry>
      </collision>
      <inertial>
        <mass value= "${straight_link_mass}"/>
        <inertia ixx="2.5229E-05" ixy="4.9094E-09" ixz="-4.3357E-08" iyy="2.2844E-05" iyz="2.9677E-06" izz="3.5161E-06"/>
        <origin xyz="0 0 0"  rpy="0 0 0" />
      </inertial>
    </link>

    <joint name="${prefix}right_finger" type="revolute">
      <parent link="${prefix}rightTilted_link" />
      <child link = "${prefix}right_finger" />
      <origin xyz="0.07358 0.01 -0.01452" rpy="${pi} ${pi} 0" />
      <axis xyz="0 1 0" />
      <limit lower="${0}" upper="${1.6}" effort="54.0" velocity="3.2"/>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>

    <link name="${prefix}right_finger">
      <visual>
        <geometry>
          <mesh filename="package://suii_description/meshes/suii/visual/finger.STL"/>
        </geometry>
        <material name="LightGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://suii_description/meshes/suii/collision/finger.STL"/>
        </geometry>
      </collision>
      <inertial>
        <mass value= "${finger_mass}"/>
        <inertia ixx="3.0184E-06" ixy="-2.1488E-06" ixz="-2.0304E-06" iyy="1.6193E-05" iyz="-2.3521E-07" izz="1.7863E-05"/>
        <origin xyz="0 0 0"  rpy="0 0 0" />
      </inertial>
    </link>

    <joint name="${prefix}left_finger" type="revolute">
      <parent link="${prefix}leftTilted_link" />
      <child link = "${prefix}left_finger" />
      <origin xyz="-0.07358 -0.01 -0.01452" rpy="${pi} ${pi} ${pi}" />
      <axis xyz="0 1 0" />
      <limit lower="${0}" upper="${1.6}" effort="54.0" velocity="3.2"/>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>

    <link name="${prefix}left_finger">
      <visual>
        <geometry>
          <mesh filename="package://suii_description/meshes/suii/visual/finger.STL"/>
        </geometry>
        <material name="LightGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://suii_description/meshes/suii/collision/finger.STL"/>
        </geometry>
      </collision>
      <inertial>
        <mass value= "${finger_mass}"/>
        <inertia ixx="3.0184E-06" ixy="-2.1488E-06" ixz="-2.0304E-06" iyy="1.6193E-05" iyz="-2.3521E-07" izz="1.7863E-05"/>
        <origin xyz="0 0 0"  rpy="0 0 0" />
      </inertial>
    </link>

    <gazebo>
 	 <plugin name="mimic" filename="libroboticsgroup_gazebo_mimic_joint_plugin.so">
	    <joint>${prefix}leftTilted_link</joint>
	    <mimicJoint>${prefix}leftStraight_link</mimicJoint>
            <multiplier>1</multiplier>
	 </plugin>
    </gazebo>

    <gazebo>
 	 <plugin name="mimic2" filename="libroboticsgroup_gazebo_mimic_joint_plugin.so">
	    <joint>${prefix}rightTilted_link</joint>
	    <mimicJoint>${prefix}rightStraight_link</mimicJoint>
            <multiplier>1</multiplier>
	 </plugin>
    </gazebo>

    <gazebo>
 	 <plugin name="mimic3" filename="libroboticsgroup_gazebo_mimic_joint_plugin.so">
	    <joint>${prefix}leftTilted_link</joint>
	    <mimicJoint>${prefix}left_finger</mimicJoint>
            <multiplier>-1</multiplier>
	 </plugin>
    </gazebo>

    <gazebo>
 	 <plugin name="mimic4" filename="libroboticsgroup_gazebo_mimic_joint_plugin.so">
	    <joint>${prefix}rightTilted_link</joint>
	    <mimicJoint>${prefix}right_finger</mimicJoint>
            <multiplier>1</multiplier>
	 </plugin>
    </gazebo>



    <link name="sonar_link">
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://suii_description/meshes/suii/collision/leftStraight_link.stl"/>
        </geometry>
      </collision>
      <inertial>
        <mass value= "${frame_mass}"/>
        <inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0" iyz="0" izz="0"/>
        <origin xyz="0 0 0"  rpy="0 0 0" />
      </inertial>
    </link>

    <!-- sonar joint -->
    <joint name="sonar_joint" type="fixed">
      <axis xyz= "0 1 0" />
      <origin xyz="-0.275 0 0.1" rpy="0 0 3.1415926535897931"/>
      <parent link="${prefix}base_link"/>
      <child link="sonar_link"/>
    </joint>

    <!-- Hokuyo Laser -->
    <link name="hokuyo_link_back">
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="0.01 0.01 0.01"/>
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${laser_link} ${laser_link} ${laser_link}"/>
        </geometry>
        <material name="red"/>
      </visual>

      <inertial>
        <mass value="1e-5" />
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
      </inertial>
    </link>

    <!-- laser joint -->
    <joint name="hokuyo_joint_back" type="fixed">
      <axis xyz="0 1 0" />
      <origin xyz="0.240 0.171 0.18" rpy="0 0 ${pi/4}"/>
      <parent link="${prefix}base_link"/>
      <child link="hokuyo_link_back"/>
    </joint>

    <!-- Hokuyo Laser -->
    <link name="hokuyo_link_front">
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="0.01 0.01 0.01"/>
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${laser_link} ${laser_link} ${laser_link}"/>
        </geometry>
        <material name="red"/>
      </visual>

      <inertial>
        <mass value="1e-5" />
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
      </inertial>
    </link>

    <!-- laser joint -->
    <joint name="hokuyo_joint_front" type="fixed">
      <axis xyz="0 1 0" />
      <origin xyz="-0.240 -0.171 0.18" rpy="0 0 ${pi/4 + pi}"/>
      <parent link="${prefix}base_link"/>
      <child link="hokuyo_link_front"/>
    </joint>

    <!-- Camera -->
    <joint name="${prefix}camera_joint" type="fixed">
      <axis xyz="0 1 0" />
      <origin xyz="0.0 -0.045 -0.1" rpy="0 ${pi/2} ${-pi/2}"/>
      <parent link="${prefix}gripper_base"/>
      <child link="${prefix}camera_link"/>
    </joint>

    <link name="${prefix}camera_link">
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
           <box size="0.010 0.121 0.018"/>
        </geometry>
      </collision>
      <visual>
        <geometry>
  	       <box size="0.010 0.121 0.018"/>
        </geometry>
        <material name="red">
          <color rgba="0.8 0.0 0.0 1.0"/>
        </material>
      </visual>
      <inertial>
        <mass value="1e-5" />
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia ixx="0" ixy="0" ixz="0" iyy="0" iyz="0" izz="0" />
      </inertial>
    </link>

    <!-- generate an optical frame http://www.ros.org/reps/rep-0103.html#suffix-frames
        so that ros and opencv can operate on the camera frame correctly -->
    <joint name="${prefix}camera_optical_joint_2D" type="fixed">
      <!-- these values have to be these values otherwise the gazebo camera image
          won't be aligned properly with the frame it is supposedly originating from -->
      <axis xyz="0 1 0" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <parent link="${prefix}camera_link"/>
      <child link="${prefix}camera_link_optical_2D"/>
    </joint>

    <joint name="${prefix}camera_optical_joint_3D" type="fixed">
      <!-- these values have to be these values otherwise the gazebo camera image
          won't be aligned properly with the frame it is supposedly originating from -->
      <axis xyz="0 1 0" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <parent link="${prefix}camera_link"/>
      <child link="${prefix}camera_link_optical_3D"/>
    </joint>

    <link name="${prefix}camera_link_optical_2D">
    </link>

    <link name="${prefix}camera_link_optical_3D">
    </link>

    <xacro:suii_transmission prefix="${prefix}" hw_interface="${transmission_hw_interface}" />
    <xacro:suii_gazebo prefix="${prefix}" />

  </xacro:macro>

</robot>
